name: Chenyx
title: Chenyx | A blog
description: To record my everyday work about AI, including finding new AI tools, building AI agents or workflow, etc.
tags:
  - blog
  - AI tools
  - AI agent
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: 824611264@qq.com
# See: https://disqus.com/
disqus_username: chenyx
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: chenyx
